# Generated by Django 5.2.2 on 2025-06-06 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('has_changing_room', models.BooleanField(default=False)),
                ('has_restaurant', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SwimWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance_meters', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('stroke_type', models.CharField(choices=[('freestyle', 'Freestyle'), ('breaststroke', 'Breaststroke'), ('backstroke', 'Backstroke'), ('butterfly', 'Butterfly'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
